config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :projects
  
  root 'pages#index'
  get "pages/about" => "pages#about"
  
  
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/422", :to => "errors#reject", :via => :all
  match "/500", :to => "errors#unexpected", :via => :all
  get "*all" => "pages#index"

    resources :standards
    resources :perf_exps

  resources :dashboard    

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
  has_many :projects
  has_many :perf_exps, through: :projects
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = current_user
    @perf_exps = PerfExp.all
    @covered_perf_exps = []
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="container">

    <% PerfExp.all.collect(&:grade_level).uniq.each do |grade_level| %>

        <h1 class="text-center"><%= "Grade Level: " + grade_level %></h1>
    
       <div class="row">
            <div class="col-md-6 text-right">Projects</div>
            <div class="col-md-6 text-left">Performance Expectations</div>

            <% @user.projects.grade_level(grade_level).each do |project| %>
                <div class="col-md-6 text-right">
                    <%= link_to "#{project.title}", project_path(project.id) %>
                </div>
                <div class="col-md-6 text-left">
                    <% project.perf_exps.each do |perf_exp| %>
                        <% @covered_perf_exps << perf_exp %>
                        <%= perf_exp.code + ": " + perf_exp.name %><br>
                    <% end %>
                </div>                
            <% end %>
        </div>
        <br>
        <div class="row">
            <div class="col-md-6 text-right">Outstanding Performance Expectations</div>
            <div class="col-md-6 text-left">Links to Projects</div>
            
            <% @perf_exps.grade_level(grade_level).excluding(@covered_perf_exps).each do |perf_exp2| %>
                <div class="col-md-6 text-right">
                    <%= perf_exp2.code %>
                </div>
                <div class="col-md-6 text-left">
                    <%= link_to "Pick a project!", projects_path( :perf_exp_ids => perf_exp2.id ) %>
                </div>
            <% end %>
        </div>    
    
    <% end %>

</div>