config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :projects
  
  root 'pages#index'
  get "pages/about" => "pages#about"
  
  
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/422", :to => "errors#reject", :via => :all
  match "/500", :to => "errors#unexpected", :via => :all
  get "*all" => "pages#index"

    resources :standards
    resources :perf_exps

  resources :dashboard    

end

app/models/perf_exp.rb
class PerfExp < ActiveRecord::Base
    has_and_belongs_to_many :standards
    has_and_belongs_to_many :projects
    has_many :users, through: :projects

    scope :grade_level, -> (grade_level) { where grade_level: grade_level }
    scope :named, -> (name) { where name: name }
    scope :excluding, -> (*values) {
        where(
            "#{table_name}.id NOT IN (?)", (
                values.compact.flatten.map { |e|
                    if e.is_a?(Integer)
                        e
                    else
                        e.is_a?(self) ? e.id : raise("Element not the same type as #{self}.")
                    end
                } << 0
            )
        )
    }
end

app/controllers/perf_exps_controller.rb
class PerfExpsController < ApplicationController
  before_filter :page_restrict

    def new
        @PerfExp = PerfExp.new
    end
    
    def index
        @PerfExps = PerfExp.where(nil)
        @PerfExps = @PerfExps.grade_level(params[:grade_level]) if params[:grade_level].present?
        @PerfExps = @PerfExps.named(params[:name]) if params[:name].present?
    end
    
    def create
        @PerfExp = PerfExp.new(params[:perf_exp])
        if @PerfExp.save
            redirect_to @PerfExp
        else
            render "new"
        end
    end
    
    private
    def perf_exp_params
        params.require(:perf_exp).permit(:name, :description, :grade_level => [], :standard_ids => [])
    end

end

app/helpers/perf_exps_helper.rb
module PerfExpsHelper
end

app/views/perf_exps/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <% PerfExp.all.collect(&:grade_level).uniq.each do |lev| %>
                <%= link_to "Grade #{lev}", perf_exps_path( :grade_level => lev ) %><br>
            <% end %>
        </div>
        <div class="col-md-6">
            <% PerfExp.all.collect(&:name).uniq.each do |nem| %>
                <%= link_to nem, perf_exps_path( :name => nem ) %><br>
            <% end %>
        </div>
    </div>
</div>

<br>
<%= link_to "Reset Filter", perf_exps_path %>
<br>

<div class="table-responsive">
    <table class="table">
        <tr>
            <th>code</th>
            <th>projects.any?</th>
            <th>projects_path( :perf_exp_ids => pe.id )</th>
            <th>name</th>
            <th>descriptiondescriptiondescriptiondescription</th>
            <th>grade_level</th>
            <th>id</th>
            <th>standard.id standard.path: standard.description</th>
            <th>project_ids</th>
        </tr>
        <% @PerfExps.each do |pe| %>
            <tr>
                <td class="text-nowrap"><%= pe.code %></td>
                <td><%= pe.projects.any? %></td>
                <td><%= link_to "link_to projects", projects_path( :perf_exp_ids => pe.id ) %></td>
                <td class="text-nowrap"><%= pe.name %></td>
                <td><%= pe.description %></td>
                <td><%= pe.grade_level %></td>
                <td><%= pe.id %></td>
                <td class="text-nowrap">
                    <% pe.standards.each do |s| %>
                    <%= s.id.to_s + " " + s.path + ": " + s.description %><br>
                    <% end %>
                </td>
                <td><%= pe.project_ids %></td>
            </tr>
        <% end %>
    </table>
</div>