config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :projects
  
  root 'pages#index'
  get "pages/about" => "pages#about"
  
  
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/422", :to => "errors#reject", :via => :all
  match "/500", :to => "errors#unexpected", :via => :all
  get "*all" => "pages#index"

    resources :standards
    resources :perf_exps

  resources :dashboard    

end

app/models/project.rb
class Project < ActiveRecord::Base
    has_and_belongs_to_many :standards
    has_and_belongs_to_many :perf_exps
    belongs_to :user

    def self.search(search)
      where("title iLIKE ? OR summary iLIKE ?", "%#{search}%", "%#{search}%") 
      #where("summary LIKE ?", "%#{search}%")
    end

    def self.include_perf_exps(perf_exp_ids)
	members = []
        Project.all.each do |project|
           members << project if project.perf_exp_ids.include? perf_exp_ids.to_i
        end
        return members
    end

    scope :grade_level, -> (grade_level) { where grade_level: grade_level }

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :page_restrict
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @subjects = Subject.all
    if params[:subject].present?
        @selected_subject = Subject.find(params[:subject]);
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end
    
  #def show(add_to_cart)
  #        if(add_to_cart)
  #            project = Project.find(params(:project))
  #            @cart.shopping_cart << project.title
  #        end
  #end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    time = Time.new
    hash = rand(65535).to_s(16)
    objKey = "project_images/" + hash.to_s + "-" + time.year.to_s + "-" + time.month.to_s + "-" + time.day.to_s + "-" + time.hour.to_s + "-" + time.min.to_s + ".jpg"
      obj = PROJECT_IMAGES.object(objKey)
      #obj.upload_file(:file)
      #File.open(:file, 'rb') do |file|
      uploaded_io = params[:project][:picture]
      File.open(uploaded_io.path, 'rb') do |file|
        obj.put(body: file)
      end
      
    @project = Project.new(project_params)
    @project.image = 'https://s3-us-west-2.amazonaws.com/diagon-alley-devel-storage/' + objKey
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        # format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        # format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        # format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        # format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end
    
  def added
    @project = Project.find(params[:id])
    if user_signed_in?
      current_user.projects << @project
    end
    #Rails.application.routes.url_helpers.project_path(:project)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
        begin
            @project = Project.find(params[:id])
        rescue ActiveRecord::RecordNotFound
            not_found
        end
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :contents, :price, :summary, :instructions, :standard_ids => [], :perf_exp_ids => [])
    end
    
    def not_found
        render :file => "#{Rails.root}/public/404.html",  :status => 404
    end
    
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.label :title %> 
<br>
<%= f.text_field :title %> 
<br>

<%= f.label :summary %> 
<br>
<%= f.text_area :summary %> 
<br>

<%= f.label :description %>
<br>
<%= f.text_area :description %>
<br>

<%= f.label :contents %>
<br>
<%= f.text_area :contents %>
<br>

<%= f.label :instructions %> 
<br>
<%= f.text_area :instructions %> 
<br>

<%= f.label :price %>
<br>
<%= f.text_field :price %>
<br>

<br>
 <%= f.submit class: 'btn btn-primary' %>

<%= f.label :picture %>
<br>
<%= f.file_field :picture %>
<br>

 <%= f.submit class: 'btn btn-default' %>

<br>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <%= f.collection_check_boxes(:standard_ids, Standard.all, :id, :path) do |b| %>
                <%= b.label {b.check_box + b.text} %><br>
            <% end %>
        </div>
        <div class="col-md-6">
            <%= f.collection_check_boxes(:perf_exp_ids, PerfExp.all, :id, :code) do |p| %>
                <%= p.label {p.check_box + p.text} %><br>
            <% end %>
        </div>
    </div
</div>
<% end %>

app/views/projects/_sidebar.html.erb
  
<nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
            <ul class="nav sidebar-nav">
                <li>
                    <br>
                    <center>
                        <span  style="font-size:28px;">
                            Project Explorer
                        </span>
                    </center>
                </li>
                <li>
                    <center>
                        <span style="font-size:24px;">
                            Subject(s)
                            <br><br>
                        </span>
                    </center>
                    <span>
                        
                        <% @subjects.each do |sub| %>
                        
                        <%if defined?(@selected_subject)%>
                        <%if sub == @selected_subject%>
                        
                        <label for=<%=sub.name%> class="btn btn-info subfield" style="background: <%=sub.color%>; width:100%;text-align:right;"><%=sub.name%><input type="checkbox" checked id=<%=sub.name%> class="badgebox" value=<%=sub.id%>><span class="badge">&check;</span></label>
                        
                        <% else %>
                        
                        <label for=<%=sub.name%> class="btn btn-info subfield" style="background: <%=sub.color%>; width:100%;text-align:right;"><%=sub.name%><input type="checkbox" !checked id=<%=sub.name%> class="badgebox" value=<%=sub.id%>><span class="badge">&check;</span></label>
                                
                        <% end %>
                        <% else %>
                        
                        <label for=<%=sub.name%> class="btn btn-info subfield" style="background: <%=sub.color%>; width:100%;text-align:right;"><%=sub.name%><input type="checkbox" checked id=<%=sub.name%> class="badgebox" value=<%=sub.id%>><span class="badge">&check;</span></label>
                        <% end %>
                        <% end %>
                    </span>
                    
                    
                </li>
                <li>
                    <center>
                        <span style="font-size:24px;">
                            Grade Level
                        </span>
                        <br><br>
                        <span style="background:transparent;">
                            <%= text_field_tag "ex2", nil, type: 'text',class:'input-large grade-slider',
                                data: {'slider-id' => 'ex1Slider',
                                    'slider-min' => '0',
                                    'slider-max' => '12',
                                    'slider-step' => '1',
                                    'slider-value' => '[0,12]' }%>
                        </span>
                    </center>
                    
                </li>
                <li>
                    <a href="#">Select NGSS Standards</a>
                </li>
                <li>
                    <a href="#">Duration Slider</a>
                </li>

                <li>
                    <center>
                        <span style="font-size:24px;">
                            Price Slider
                            <br><br>
                        </span>
                        <span>
                            <input type="text" value="Enter a Max Price" class="input-large" id="price-filter" style="color:#888">
                        </span>
                    </center>
                </li>
                <li>
                    <a href="#">Reusable Checkbox</a>
                </li>
                <!-- No need for a button
                <li>
                    <%= submit_tag "Search", :class => "btn btn-primary" ,:style => "width:100%;"%>
                </li>
-->
<!-- 				 <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Works <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li class="dropdown-header">Dropdown heading</li>
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li -->
            </ul>
        </nav>

app/views/projects/_standards.html.erb
<!-- this will eventually need different flow controls for different standard sets but for now assumes NGSS -->

<h3>Performance Expectations:</h3>
<% @project.perf_exps.each do |pe| %>
    <h4><%= pe.code + ": " + pe.name %></h4>
    <h3><%= pe.description %></h3>
<% end %>

app/views/projects/added.html.erb
<h1><%= @project.title %> Added!</h1>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<head>
</head>
<body>
    <div class="col-sm-6 col-sm-offset-3">
    </div>
    <div class="col-sm-3">
        <input type="search" id="search" value="search" style="color:#888"/>
    </div>
    <!-- Tiles -->
    <section id="tile" class="bg-light-gray">
        <div class="container">
        <% @projects.each do |project| %>
            <div class="col-md-4 col-sm-6 tile-item project-panel">
                <a href=<%= project_path(project) %> class="tile-link"><!-- data-toggle="modal"-->
                    <div class="tile-hover">
                        <div class="tile-hover-content">
                            <i class="fa fa-plus fa-3x"></i>
                        </div>
                    </div>
                    <img src= <%= project.image %> class="img-responsive" alt="">
                    <div class="tile-caption">
                        <h4 class="project-title"><%= project.title %></h4>
                        <p class="project-summary"><%=project.summary%></p>
                        <p2>(tags)</p2>
                        <p3>$<%=project.price%></p3>
                    </div>
                </a>
                <% project.tags.each do |tag| %>
                    <div class="tag" hidden><%=tag%></div>
                <% end %>
                <div class="grade-level" hidden><%=project.grade_level%></div>
                </div>
            <% end %>
        </div>
        <div class = "col-sm-12 col-md-offset-3">
            <%= button_to 'New Project', new_project_path, :class =>'btn btn-primary', :method => :get %>
        </div>
    </section>
</body>

<!-- <button type="button" class="btn btn-primary btn-lg btn-block"><%= link_to 'New Project', new_project_path %></button> -->

app/views/projects/new.html.erb
<div class = "col-sm-9 col-md-offset-2">
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path, style: "color:white" %>

</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project), style: "color: snow" %> |
<%= link_to 'Back', projects_path, style: "color: snow" %>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
    <section class="Jumbotron" style="background-image: url('/img/portfolio/thumbnails/Saturn.jpg');margin-bottom:30px;">
        <div class="container" style="background:#1a1a1a; padding: 20px;">
                <div class="col-sm-6 text-center">
					<h1><%= @project.title %></h1>
                    <img src = <%= @project.image %> style="width: 100%;max-width: 400px;margin:20px;">
                </div>
                <div class="col-sm-6">
                    <div class="row text-center" style= "padding-top: 20px">
                        <h3><%= @project.summary %></h3>
                    </div>
					<div class = "col-sm-6" style="padding-top:80px">
              <%= render 'standards' %>
					</div>
					<div class = "col-sm-6 text-right" style="padding-top:20px">
					 <h3> Materials (maybe order just some?)</h3>
						 <ul style="list-style-position: inside;">
						 <li>Thing 1 ($5)</li>
						 <li> Thing 2 ($999,995.00)</li<
						 </ul>
						 <!--<h3>Price:</h3>
                    <h4><%= @project.price %></h4>
					<% if user_signed_in? %>
                    <% if current_user.projects.exists? @project %>
                    <%= button_to 'Add to Cart', added_path(@project), :method => :get, :class => 'btn btn-primary', :disabled => true %>
                    <% else %>
                    <%= button_to 'Add to Cart', added_path(@project), :method => :get, :class => 'btn btn-primary' %>
                    <% end %>
                    <% end %>-->
					</div>
                </div>
            </div>
    </section>
    <section class="container" style="background:#1a1a1a; padding: 50px;">
            <figure class="col-sm-3" style="outline: 1px solid black;">
                <div class="text-center">
                    <h3>Price:</h3>
                    <h4><%= @project.price %></h4>
					<% if user_signed_in? %>
                    <% if current_user.projects.exists? @project %>
                    <%= button_to 'Add to Cart', added_path(@project), :method => :get, :class => 'btn btn-primary', :disabled => true %>
                    <% else %>
                    <%= button_to 'Add to Cart', added_path(@project), :method => :get, :class => 'btn btn-primary' %>
                    <% end %>
                    <% end %>
                </div>
            </figure>
            <figure class="col-sm-6">
                <p><%= @project.description %></p>
                <h3>Contents</h3>
                <p><%= @project.contents %></p>
                <h3>Instructions</h3>
                <p><%= @project.instructions %></p>
            </figure>
            <figure class="col-sm-3">
                <%= link_to "Workspace", workspace_path(@project), style: 'color: snow' %>
            </figure>
        </div>
    </section>
	</div>
</body>