config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :projects
  
  root 'pages#index'
  get "pages/about" => "pages#about"
  
  
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/422", :to => "errors#reject", :via => :all
  match "/500", :to => "errors#unexpected", :via => :all
  get "*all" => "pages#index"

    resources :standards
    resources :perf_exps

  resources :dashboard    

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/perf_exp.rb
class PerfExp < ActiveRecord::Base
    has_and_belongs_to_many :standards
    has_and_belongs_to_many :projects
    has_many :users, through: :projects

    scope :grade_level, -> (grade_level) { where grade_level: grade_level }
    scope :named, -> (name) { where name: name }
    scope :excluding, -> (*values) {
        where(
            "#{table_name}.id NOT IN (?)", (
                values.compact.flatten.map { |e|
                    if e.is_a?(Integer)
                        e
                    else
                        e.is_a?(self) ? e.id : raise("Element not the same type as #{self}.")
                    end
                } << 0
            )
        )
    }
end

app/models/project.rb
class Project < ActiveRecord::Base
    has_and_belongs_to_many :standards
    has_and_belongs_to_many :perf_exps
    belongs_to :user

    def self.search(search)
      where("title iLIKE ? OR summary iLIKE ?", "%#{search}%", "%#{search}%") 
      #where("summary LIKE ?", "%#{search}%")
    end

    def self.include_perf_exps(perf_exp_ids)
	members = []
        Project.all.each do |project|
           members << project if project.perf_exp_ids.include? perf_exp_ids.to_i
        end
        return members
    end

    scope :grade_level, -> (grade_level) { where grade_level: grade_level }

end

app/models/standard.rb
class Standard < ActiveRecord::Base
    has_many :children, :class_name => "Standard", :foreign_key => "parent_id"
    belongs_to :parent, :class_name => "Standard"
    accepts_nested_attributes_for :children
    has_and_belongs_to_many :perf_exps
    has_and_belongs_to_many :projects
    
    def path
        path = self.name
        current = self
        while (current.parent_id) do
            path = Standard.find(current.parent_id).name + "." + path
            current = Standard.find(current.parent_id)
        end
        return path
    end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
  has_many :projects
  has_many :perf_exps, through: :projects
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = current_user
    @perf_exps = PerfExp.all
    @covered_perf_exps = []
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
    
    def not_found
        render :file => "#{Rails.root}/public/404.html",  :status => 404
    end
    
    def reject
        render :file => "#{Rails.root}/public/422.html",  :status => 422
    end
    
    def unexpected
        render :file => "#{Rails.root}/public/500.html",  :status => 500
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
      @subjects = Subject.all
      @panel = Panel.new(S3.object("front_page/panel.xml").get().body.read)
  end
    
  def about
      
  end
end

app/controllers/perf_exps_controller.rb
class PerfExpsController < ApplicationController
  before_filter :page_restrict

    def new
        @PerfExp = PerfExp.new
    end
    
    def index
        @PerfExps = PerfExp.where(nil)
        @PerfExps = @PerfExps.grade_level(params[:grade_level]) if params[:grade_level].present?
        @PerfExps = @PerfExps.named(params[:name]) if params[:name].present?
    end
    
    def create
        @PerfExp = PerfExp.new(params[:perf_exp])
        if @PerfExp.save
            redirect_to @PerfExp
        else
            render "new"
        end
    end
    
    private
    def perf_exp_params
        params.require(:perf_exp).permit(:name, :description, :grade_level => [], :standard_ids => [])
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :page_restrict
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @subjects = Subject.all
    if params[:subject].present?
        @selected_subject = Subject.find(params[:subject]);
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end
    
  #def show(add_to_cart)
  #        if(add_to_cart)
  #            project = Project.find(params(:project))
  #            @cart.shopping_cart << project.title
  #        end
  #end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    time = Time.new
    hash = rand(65535).to_s(16)
    objKey = "project_images/" + hash.to_s + "-" + time.year.to_s + "-" + time.month.to_s + "-" + time.day.to_s + "-" + time.hour.to_s + "-" + time.min.to_s + ".jpg"
      obj = PROJECT_IMAGES.object(objKey)
      #obj.upload_file(:file)
      #File.open(:file, 'rb') do |file|
      uploaded_io = params[:project][:picture]
      File.open(uploaded_io.path, 'rb') do |file|
        obj.put(body: file)
      end
      
    @project = Project.new(project_params)
    @project.image = 'https://s3-us-west-2.amazonaws.com/diagon-alley-devel-storage/' + objKey
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        # format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        # format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        # format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        # format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end
    
  def added
    @project = Project.find(params[:id])
    if user_signed_in?
      current_user.projects << @project
    end
    #Rails.application.routes.url_helpers.project_path(:project)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
        begin
            @project = Project.find(params[:id])
        rescue ActiveRecord::RecordNotFound
            not_found
        end
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :contents, :price, :summary, :instructions, :standard_ids => [], :perf_exp_ids => [])
    end
    
    def not_found
        render :file => "#{Rails.root}/public/404.html",  :status => 404
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def header(text)
		content_for(:header) { text.to_s }
	end
	

	
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/perf_exps_helper.rb
module PerfExpsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/helpers/workspace_helper.rb
module WorkspaceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Explorious</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
  
  <nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Explorious', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', pages_about_path %></li>
      </ul>
      
      <ul class="nav navbar-nav pull-right">
        <% if admin_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              admin
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Log out', destroy_admin_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

      <%= yield %>
      <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>

  </body>
    
</html>

<style>
    .icon-size {
        font-size:15px;
    }
    .shoppingBadge-custom{
background: red;
position:absolute;
left:25px;
top:20px;
font-size:10px;

 }
</style>

app/views/pages/about.html.erb
<h1 style="text-align: center"> About Page </h1>

<link rel="stylesheet" href="/droplet.css"/>
<style>
  .button {
  display: inline-block;
  border-radius: 3px;
  background: #dddddd;
  border: 1px solid lightGrey;
}

.button:hover {
  cursor: pointer;
  background: #aaaaaa;
}

.button-text {
  padding: 2px;
  color: #666666;
}

.demo-window {
  position: relative;
  background: #3cb5f9;
  padding: 40px;
  border: 5px solid lightgrey;
  border-radius: 4pt;
}

.tab-label {
  position: absolute;
  top: -28px;
  left 0px;
  width: 150px;
  height: 28px;
  background: lightgrey;
  border-radius: 4pt;
  text-align: center;
  color: black;
}

#execute-button {
  float: right;
  margin: 5px;
}
</style>
<script src="/ace.js"></script>
<script src="/droplet-full.js"></script>
<script src="/droplet_block_definitions.js"></script>
<div class="container">
  <div class="row">
    <div class="demo-window">
      <div class="tab-label">Robot Code Editor</div>
      <div id="editor-wrapper" style="position:relative;width:100%;height:500px;border: 1px solid black;">
        <div id="editor"></div>
      </div>
      <a id="execute-button">
        <div class="button">
          <div class="button-text">Execute</div>
        </div>
      </a>
    </div>
  </div>
</div>
<script>
window.onload = function() {
var sessions = {};
var editor = new droplet.Editor(document.getElementById('editor'), modes['javascript']);
  init_text = "var ros = ros_init();\nvar velTopic = new_topic(ros, 'cmd_vel', 'geometry_msgs/Twist');\nfunction step1() {\n  var twist_msg = geometry_msgs_Twist(ros, 0.3, 0, 0, 0, 0, 0);\n  velTopic.publish(twist_msg);\n}\nfunction step2() {\n  var twist_msg = geometry_msgs_Twist(ros, 0, 0, 0, 0, 0, -0.4);\n  velTopic.publish(twist_msg);\n}\nfunction step3() {\n  var twist_msg = geometry_msgs_Twist(ros, 0, 0, 0, 0, 0, 0);\n  velTopic.publish(twist_msg);\n}\nsetTimeout(step1, 1000);\nsetTimeout(step2, 2000);\nsetTimeout(step3, 3000);";
editor.setValue(init_text);
}
</script>

app/views/pages/index.html.erb
<!-- Feel free to change literally anything here to work better with the CSS and formatting on the rest of the site-->
<!-- especially the lowest level div tag, that one's really just for me -->
<!-- I have attempted to make everything as easy to stylistically modify as possible -->
<!-- Testing was done on the following resolutions: 2560x1440, 1920x1080, 1366x768, 360x640-->
<style>
header h1#logo {
    display: inline-block;
    height: 400px;
    margin-top: 20%;
    float: left;
    font-family: "Oswald", sans-serif;
    font-size: 60px;
    color: white;
    font-weight: 400;
    -webkit-transition: all 0.3s;
    -moz-transition: all 0.3s;
    -ms-transition: all 0.3s;
    -o-transition: all 0.3s;
    transition: all 0.3s; }
</style>

<div style="text-align:center">
    <h1 id="logo">
      <img id="gif" src="/explorious-v2_noloop.gif" alt="Explorious" style="width:90%;">
    </h1>
    <!--
    <div class="jumbotron">
        <div class="container">
          <h1>Empowering Project-Based-Learning <small><br>K-12 STEM Project Kits for Teachers</small></h1>
        </div>
    </div>

    <div class="container">
       <div class="row">
            <div class="col-md-6">
                <h2><strong>What's a kit?</strong></h2>
                <h3>Highly affordable<br><small>$1-10 per student per kit</small></h3>
                <h3>Standards-integrated<br><small>NGSS, Common Core, and ISTE</small></h3>
                <h3>Completely pre-packaged<br><small>Lesson plans and materials: everything you need!</small></h3>
            </div>
           <div class="col-md-1"></div> 
           <div class="col-md-4">
                <h2><strong>Submit a project!</strong></h2>
                <h3>You know that INCREDIBLE activity you created to teach that thing you love? 
                    Submit it to the platform and get paid a cut of sales.<br>
                    <small>Subject to a painless submission process, of course.</small>
                    <br> Coming soon!
                </h3>
            <div class="col-md-1"></div>    
            </div>

        </div>
    </div>

    <div class="jumbotron">
        <div class="container">
            <h1>Get Explorious <small><br>Pick a subject below! </small></h1>
        </div>
    </div>

    <div class="jumbotron">
        <div class="container">
            <h1>How about us? <small><br>Here's why we do this</small></h1>
        </div>
    </div>

    <div class="container">
        <div clas="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <h3>We believe we can broadly increase the quality and equity of high quality STEM education by empowering teachers to spend less time and money preparing projects. We're very much a work in progress and we would love to hear from you!</h3>
                
                (Render form)
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>
    -->
</div>